---
- name: install pip
  yum: name=python-pip state=present

- name: install gcc-c++
  yum: name=gcc-c++ state=present

- name: install nodeenv
  pip: name=nodeenv state=present

- name: create nodeenv
  command: bash -c "cd /root && nodeenv zsnapper" creates=/root/zsnapper

- name: install zsnapper
  command: bash -c "source /root/zsnapper/bin/activate && npm -g install zsnapper"

- name: change node interpreter
  command: bash -c "sed -i -e \"s/#\!\/usr\/node\/bin\/node/#!\/bin\/env node/g\" /root/zsnapper/bin/zsnapper"

- name: put zsnapper config
  template: src=zsnapper.ini dest=/etc/zsnapper.ini
