---
- name: Download zsnapper
  get_url: url=https://github.com/calmh/zsnapper/releases/download/v2.0.0/zsnapper-linux-amd64.tar.gz dest=/root/zsnapper-linux-amd64.tar.gz

- name: Unpack zsnapper
  unarchive:
    src: /root/zsnapper-linux-amd64.tar.gz
    dest: /opt
    remote_src: True

- name: put zsnapper config
  template: src=zsnapper.yml dest=/etc/zsnapper.yml
  notify: restart zsnapper

- name: put systemd unit file
  template: src=zsnapper.service dest=/etc/systemd/system/zsnapper.service owner=root group=root mode=0644
  when: "(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>')))"

- name: enable zsnapper service
  service: name=zsnapper enabled=yes state=started
  when: "(ansible_distribution == 'Debian' and ansible_distribution_major_version == '8') or (ansible_distribution == 'Ubuntu' and (ansible_distribution_version|version_compare(14.04, '>')))"
